# Generated by Django 5.2.1 on 2025-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
                ('logo', models.ImageField(upload_to='homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Quarto', models.IntegerField()),
                ('qtd_Hospedes', models.IntegerField()),
                ('estilo', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casal', 'Casal'), ('Familia', 'Familia')])),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Confort', 'Confort'), ('Plus', 'Plus'), ('Premium', 'Premium')])),
                ('valor', models.FloatField(max_length=3)),
                ('descricao', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='quarto/')),
            ],
        ),
    ]
